name: Ravi Mistry
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Scribblr_42
github_username:  scribblr42
theme: minima
